# Generated by Django 4.2.4 on 2023-08-19 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actuators',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('idActuator', models.CharField(max_length=50)),
                ('typeOfActuator', models.CharField(max_length=20)),
                ('actuatorNumber', models.IntegerField()),
                ('location', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=15)),
                ('value', models.DecimalField(decimal_places=2, max_digits=4)),
                ('dateOfTest', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('idSensor', models.CharField(max_length=50)),
                ('typeOfSensor', models.CharField(max_length=20)),
                ('sensorNumber', models.IntegerField()),
                ('location', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=15)),
                ('value', models.DecimalField(decimal_places=2, max_digits=4)),
                ('dateOfTest', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('idCrop', models.CharField(max_length=50)),
                ('typeOfCrop', models.CharField(max_length=20)),
                ('CropNumber', models.IntegerField()),
                ('location', models.CharField(max_length=20)),
                ('stage', models.CharField(max_length=15)),
                ('plantingDate', models.DateTimeField()),
                ('description', models.TextField()),
                ('actuators', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stationApp.actuators')),
                ('sensors', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stationApp.sensors')),
            ],
        ),
    ]
