# Generated by Django 4.2.4 on 2023-08-19 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stationApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crops',
            name='actuators',
        ),
        migrations.RemoveField(
            model_name='crops',
            name='sensors',
        ),
    ]
