# Generated by Django 4.2.4 on 2023-08-19 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stationApp', '0002_remove_crops_actuators_remove_crops_sensors'),
    ]

    operations = [
        migrations.AddField(
            model_name='crops',
            name='actuators',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='stationApp.actuators'),
        ),
        migrations.AddField(
            model_name='crops',
            name='sensors',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='stationApp.sensors'),
        ),
    ]
