# Generated by Django 4.2.4 on 2023-08-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationApp', '0003_crops_actuators_crops_sensors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actuators',
            old_name='dateOfTest',
            new_name='installationDate',
        ),
        migrations.RenameField(
            model_name='sensors',
            old_name='dateOfTest',
            new_name='installationDate',
        ),
        migrations.AlterField(
            model_name='actuators',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='crops',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='idSensor',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
