# Generated by Django 4.2.4 on 2023-08-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationApp', '0004_rename_dateoftest_actuators_installationdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensors',
            name='idSensor',
            field=models.CharField(editable=False, max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
