# Generated by Django 4.2.4 on 2023-08-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationApp', '0005_alter_sensors_idsensor_alter_sensors_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensors',
            name='sensorNumber',
            field=models.IntegerField(editable=False),
        ),
    ]
