# Generated by Django 4.2.4 on 2023-08-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationApp', '0006_alter_sensors_sensornumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensors',
            name='idSensor',
            field=models.CharField(editable=False, max_length=70),
        ),
    ]
