# Generated by Django 4.2.4 on 2023-08-19 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationApp', '0008_remove_crops_actuators_remove_crops_sensors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensors',
            name='installationDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
